name = "PlotlyDemoPackage"
uuid = "eeeeeee1-edee-424d-aae2-cabeeee94eeb"
authors = ["fons"]
version = "1.0.0"

[deps]
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[compat]
Artifacts = "1"
Base64 = "1"
JSON = "^0.21.1"
julia = "1.10"
